<?php

namespace Recchia\HelpdeskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaRepository extends EntityRepository
{
    public function getTareasByCategoria($id)
    {
        $sql = $this->getEntityManager()
                ->createQuery("SELECT t.id, t.descripcion FROM HelpdeskBundle:Tarea t WHERE t.categoria = :categoria");
        $sql->setParameter('categoria', $id);
        
        return $sql->getArrayResult();
    }
}
